service:
  name: player-stats-serverless

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  stage: dev
  profile: chienboul-dev
  memorySize: 128
  timeout: 300

custom:
  webpack:
    includeModules: true

functions:
  # APIGateway
  players:
    handler: src/api/handlers/players.handler
    events:
      - http:
          path: /players/{any+}
          method: ANY
          cors: true
